FROM docker.io/arm64v8/ubuntu:23.10

RUN apt -y update
RUN apt -y install libgstreamermm-1.0-dev libgtkmm-3.0-dev libboost-all-dev cmake make build-essential
RUN apt -y install libasound2-dev
RUN apt -y install alsa-utils dbus-x11
RUN apt -y install adwaita-icon-theme-full gnome-icon-theme-nuovo tango-icon-theme
RUN apt -y install gtk-update-icon-cache



